"""
Sweep 3 candidate list: 40 candidate skills + 20 candidate MCP servers a
CCIE-level network agent should plausibly have, picked by inspecting the 227
existing workspace/skills/ entries and the mcp-servers/ directory for gaps.
Excludes anything already covered by an existing skill/MCP by name.
"""

CANDIDATE_SKILLS = [
    ("cisco-sdwan-vmanage-ops", "Manage Cisco Catalyst SD-WAN (vManage/vEdge) fabric: device templates, policies, and vEdge/cEdge health."),
    ("juniper-mist-ops", "Manage Juniper Mist cloud-managed wireless/wired/SD-WAN: AP health, RRM insights, Marvis AI troubleshooting."),
    ("aruba-central-ops", "Manage HPE Aruba Central cloud dashboard: AP/switch/gateway health, group config, guest access."),
    ("extreme-cloudiq-ops", "Manage Extreme Networks ExtremeCloud IQ: switch/AP fleet health, ELRP, fabric visibility."),
    ("thousandeyes-path-visibility", "Cisco ThousandEyes synthetic path and app visibility tests and alerts."),
    ("cisco-umbrella-dns-security", "Cisco Umbrella DNS security policy, block lists, and investigate-console lookups."),
    ("solarwinds-npm-ops", "SolarWinds NPM/NCM device monitoring, config backup, and alerting."),
    ("librenms-observability", "LibreNMS open-source network monitoring: device health, alerting, port graphs."),
    ("citrix-netscaler-adc-ops", "Citrix ADC (NetScaler) load balancer config, vServer health, and troubleshooting."),
    ("haproxy-nginx-lb-ops", "HAProxy/Nginx software load balancer config and health checks."),
    ("tenable-nessus-vuln-scan", "Tenable Nessus vulnerability scanning and scan-result triage."),
    ("qualys-vuln-management", "Qualys vulnerability management scanning and asset risk scoring."),
    ("microsoft-sentinel-siem", "Microsoft Sentinel SIEM incident triage, KQL hunting queries, and alert correlation."),
    ("okta-identity-ops", "Okta identity/SSO admin: user lifecycle, app assignment, and MFA policy."),
    ("entra-id-conditional-access", "Microsoft Entra ID conditional access policy review and sign-in log triage."),
    ("cisco-secure-endpoint-amp", "Cisco Secure Endpoint (AMP) malware event triage and device isolation."),
    ("cisco-duo-mfa-ops", "Cisco Duo MFA policy, device trust, and authentication log review."),
    ("gigamon-packet-broker-ops", "Gigamon/Ixia network packet broker (TAP/SPAN aggregation) config and health."),
    ("ekahau-wifi-site-survey", "Wi-Fi site survey (Ekahau) import/analysis for RF planning and validation."),
    ("iperf-throughput-testing", "iPerf network throughput and latency benchmarking between endpoints."),
    ("dns-diagnostics", "Generic DNS diagnostics: dig/nslookup/trace, propagation checks, and record validation."),
    ("phpipam-address-management", "phpIPAM open-source IP address management operations."),
    ("cisco-stealthwatch-nsa", "Cisco Secure Network Analytics (Stealthwatch) NetFlow-based threat detection triage."),
    ("zeek-suricata-nsm", "Zeek/Suricata network security monitoring rule review and alert triage."),
    ("config-drift-detection", "Cross-vendor running-vs-golden-config drift detection and compliance scoring."),
    ("firmware-upgrade-orchestration", "Multi-vendor network device firmware/OS upgrade planning and orchestration."),
    ("cisco-smart-licensing-ops", "Cisco Smart Licensing usage, compliance, and license pool management."),
    ("catc-sda-fabric-provisioning", "Cisco Catalyst Center SD-Access fabric provisioning (write operations: fabric sites, virtual networks, policy)."),
    ("cisco-wlc-9800-ops", "Cisco Catalyst 9800 / AireOS WLC direct wireless controller operations."),
    ("aruba-clearpass-nac", "Aruba ClearPass network access control policy and endpoint profiling."),
    ("hashicorp-consul-service-mesh", "HashiCorp Consul service mesh and service discovery configuration and health."),
    ("istio-envoy-service-mesh", "Istio/Envoy service mesh traffic policy and mTLS troubleshooting."),
    ("cilium-ebpf-network-policy", "Cilium eBPF-based Kubernetes network policy and Hubble flow visibility."),
    ("capacity-bandwidth-forecasting", "Network capacity planning and bandwidth utilization forecasting."),
    ("maintenance-window-conflict-checker", "Cross-system change/maintenance window conflict detection across multiple ITSM/change sources."),
    ("compliance-framework-mapping", "Map network controls to compliance frameworks (PCI-DSS, NIST 800-53, ISO 27001)."),
    ("chaos-engineering-network-resilience", "Chaos engineering / fault injection testing for network resilience validation."),
    ("cisco-cucm-voice-ops", "Cisco Unified Communications Manager (CUCM) dial-plan and device operations."),
    ("email-security-gateway-ops", "Email security gateway (Proofpoint/Mimecast) threat and quarantine triage."),
    ("corelight-network-detection", "Corelight network detection and response (Zeek-based) alert triage."),
]

CANDIDATE_MCPS = [
    ("juniper-mist-mcp", "Juniper Mist cloud API MCP server for wireless/wired/SD-WAN management."),
    ("aruba-central-mcp", "Aruba Central cloud API MCP server for AP/switch/gateway management."),
    ("solarwinds-mcp", "SolarWinds Orion API MCP server for NPM/NCM monitoring and config backup."),
    ("librenms-mcp", "LibreNMS REST API MCP server for open-source network monitoring."),
    ("tenable-nessus-mcp", "Tenable.io/Nessus API MCP server for vulnerability scanning."),
    ("microsoft-sentinel-mcp", "Microsoft Sentinel/Log Analytics KQL API MCP server for SIEM queries."),
    ("okta-mcp", "Okta admin API MCP server for identity/SSO management."),
    ("entra-id-mcp", "Microsoft Graph Entra ID API MCP server for conditional access and sign-in logs."),
    ("cisco-umbrella-mcp", "Cisco Umbrella API MCP server for DNS security policy and investigate lookups."),
    ("cisco-secure-endpoint-mcp", "Cisco Secure Endpoint (AMP) API MCP server for malware event triage."),
    ("cisco-duo-mcp", "Cisco Duo Admin API MCP server for MFA policy and auth log review."),
    ("citrix-netscaler-mcp", "Citrix ADC (NetScaler) NITRO API MCP server for load balancer config."),
    ("gigamon-mcp", "Gigamon GigaVUE-FM API MCP server for packet broker management."),
    ("hashicorp-consul-mcp", "HashiCorp Consul HTTP API MCP server for service mesh/discovery."),
    ("istio-envoy-mcp", "Istio/Envoy control-plane API MCP server for service mesh traffic policy."),
    ("cilium-hubble-mcp", "Cilium/Hubble observability API MCP server for eBPF network policy and flow visibility."),
    ("phpipam-mcp", "phpIPAM REST API MCP server for IP address management."),
    ("qualys-mcp", "Qualys VM API MCP server for vulnerability management."),
    ("cisco-cucm-mcp", "Cisco Unified CM AXL/Serviceability API MCP server for voice/dial-plan operations."),
    ("gremlin-chaos-mcp", "Gremlin chaos engineering API MCP server for resilience fault injection."),
]
